export interface BuiltinInfo { tag: string; defaultClass?: string; voidEl?: boolean }

export const BUILTIN_MAP: Record<string, BuiltinInfo> = {
  // structural
  Main:        { tag: "main" },
  Header:      { tag: "header" },
  Footer:      { tag: "footer" },
  Nav:         { tag: "nav" },
  Section:     { tag: "section" },
  Article:     { tag: "article" },
  Aside:       { tag: "aside" },
  Div:         { tag: "div" },
  Span:        { tag: "span" },
  Hero:        { tag: "section", defaultClass: "hero" },
  Container:   { tag: "div",     defaultClass: "container" },
  Grid:        { tag: "div",     defaultClass: "grid" },
  Flex:        { tag: "div",     defaultClass: "flex" },
  Stack:       { tag: "div",     defaultClass: "stack" },
  Row:         { tag: "div",     defaultClass: "row" },
  Column:      { tag: "div",     defaultClass: "col" },
  CardGrid:    { tag: "div",     defaultClass: "card-grid" },
  // typography
  Heading:     { tag: "h1" },
  SubHeading:  { tag: "p",      defaultClass: "subheading" },
  Paragraph:   { tag: "p" },
  Lead:        { tag: "p",      defaultClass: "lead" },
  Small:       { tag: "small" },
  Strong:      { tag: "strong" },
  Em:          { tag: "em" },
  Code:        { tag: "code" },
  Pre:         { tag: "pre" },
  Blockquote:  { tag: "blockquote" },
  Mark:        { tag: "mark" },
  Label:       { tag: "label" },
  Abbr:        { tag: "abbr" },
  Del:         { tag: "del" },
  Ins:         { tag: "ins" },
  Sub:         { tag: "sub" },
  Sup:         { tag: "sup" },
  Data:        { tag: "data" },
  Time:        { tag: "time" },
  Bdi:         { tag: "bdi" },
  Bdo:         { tag: "bdo" },
  Cite:        { tag: "cite" },
  Dfn:         { tag: "dfn" },
  Kbd:         { tag: "kbd" },
  Samp:        { tag: "samp" },
  Var:         { tag: "var" },
  Address:     { tag: "address" },
  Ruby:        { tag: "ruby" },
  Rt:          { tag: "rt" },
  Rp:          { tag: "rp" },
  // interactive
  Button:      { tag: "button" },
  Link:        { tag: "a" },
  NavLink:     { tag: "a" },
  Select:      { tag: "select" },
  Form:        { tag: "form" },
  Fieldset:    { tag: "fieldset" },
  Legend:      { tag: "legend" },
  Details:     { tag: "details" },
  Summary:     { tag: "summary" },
  Dialog:      { tag: "dialog" },
  Textarea:    { tag: "textarea" },
  Datalist:    { tag: "datalist" },
  Optgroup:    { tag: "optgroup" },
  Option:      { tag: "option" },
  Progress:    { tag: "progress" },
  Meter:       { tag: "meter" },
  Output:      { tag: "output" },
  Map:         { tag: "map" },
  // media
  Picture:     { tag: "picture" },
  Video:       { tag: "video" },
  Audio:       { tag: "audio" },
  Figure:      { tag: "figure" },
  Figcaption:  { tag: "figcaption" },
  Canvas:      { tag: "canvas" },
  Svg:         { tag: "svg" },
  IFrame:      { tag: "iframe" },
  Object:      { tag: "object" },
  // void elements
  Img:         { tag: "img",    voidEl: true },
  Logo:        { tag: "img",    voidEl: true },
  Input:       { tag: "input",  voidEl: true },
  Checkbox:    { tag: "input",  voidEl: true },
  Hr:          { tag: "hr",     voidEl: true },
  Br:          { tag: "br",     voidEl: true },
  Wbr:         { tag: "wbr",   voidEl: true },
  Source:      { tag: "source", voidEl: true },
  Embed:       { tag: "embed",  voidEl: true },
  Col:         { tag: "col",    voidEl: true },
  Area:        { tag: "area",   voidEl: true },
  // lists
  Ul: { tag: "ul" }, Ol: { tag: "ol" }, Li: { tag: "li" },
  Dl: { tag: "dl" }, Dt: { tag: "dt" }, Dd: { tag: "dd" },
  // tables
  Table:       { tag: "table" },
  Caption:     { tag: "caption" },
  Thead:       { tag: "thead" },
  Tbody:       { tag: "tbody" },
  Tfoot:       { tag: "tfoot" },
  Tr:          { tag: "tr" },
  Th:          { tag: "th" },
  Td:          { tag: "td" },
  Colgroup:    { tag: "colgroup" },
  // utility
  Template:    { tag: "template" },
  Slot:        { tag: "slot" },
  NoScript:    { tag: "noscript" },
  RawHTML:     { tag: "__RAW__" },
};

export const VOID_TAGS = new Set([
  "area","base","br","col","embed","hr","img","input",
  "link","meta","param","source","track","wbr",
]);